import Head from 'next/head'
import Sidebar from '../components/1-Sidebar/Sidebar'
import Hero from '../components/2-Hero/Hero'
import About from '../components/3-About/About'
import Services from '../components/4-Services/Services'
import Resume from '../components/5-Resume/Resume'
import Client from '../components/6-Clients/Client'
import Portfolio from '../components/7-Portfolio/Portfolio'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Sidebar>
          <Hero />
          <About/>
          <Services/>
          <Resume/>
          <Client/>
          <Portfolio/>
        </Sidebar>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
